# **NUMPY NOTEBOOK BY KAVIN**

**HOW TO CREATE NUMPY ARRAYS**

np.array is a function that is used to create a numpy array

In [1]:
import numpy as np

chennai = np.array([73,67,43])
chennai

array([73, 67, 43])

In [2]:
type(chennai)

numpy.ndarray

In [3]:
weights = np.array([0.3, 0.5, 0.2])
weights

array([0.3, 0.5, 0.2])

In [4]:
type(weights)

numpy.ndarray

**Just like normal arrays or lists, the first element is the zeroth index**

In [5]:
print(weights[1])
print(chennai[0])

0.5
73


**OPERATIONS BY NUMPY**

DOT PRODUCT 
* **np.dot(variable_1,variable_2)** is used to compute the dot product between two variables
*  It can also be done through first multiplication with weights and then adding the next elements
   (chennai*weights).sum() 
*  The * operator is used to calculate the product of two numpy arrays if they both are in same size
*  The sum method **.sum()** is used to find the sum of elements in a matrix
   


In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.dot(arr1, arr2))     #Computes the dot product
print(arr1*arr2)              #Multiplication of two matrices
print((arr1 *arr2).sum())     #Other way for computing dot product

print(arr1.sum())            #Sum of elements in array 1

32
[ 4 10 18]
32
6


**BENEFITS OF NUMPY ARRAYS compared to python lists**

**Easy declaration** -> It is easy to declare numpy arrays and it is compatible for performing mathematical operations rather than defining loops and functions in python

**Performance** -> Numpy operations are internally coded in C++ so the execution is fast compared to the python loops and functions

**MULTIDIMENSIONAL NUMPY ARRAYS**
* .shape is used to find the dimension of the matrix in 2D multidimensional numpy arrays


In [7]:
climate_data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(climate_data)
print(climate_data.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [8]:
arr_3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3D)
print(arr_3D.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


**All the elements in a numpy array should have the same data type. It can be checked using .dtype**

In [9]:
countries = np.array(["India", "China", "Pakistan", "Sri Lanka"])
print(countries.dtype)

print(weights.dtype)

<U9
float64


**Matrix multiplication**

It can be done using np.matmul(mat_1, mat_2) or mat_1 @ mat_2

In [10]:
np.matmul(climate_data, weights)


array([1.9, 4.9, 7.9])

In [11]:
climate_data @ weights

array([1.9, 4.9, 7.9])

**MATRIX OPERATIONS USING NUMPY**

In [12]:
numpy_arr1 = np.array([[20,21,22,23,24], 
                       [21,22,23,24,25], 
                       [22,23,24,25,26]])
numpy_arr2 = np.array([[1,2,3,4,5],
                       [2,3,4,5,6],
                       [3,4,5,6,7]])

##Addition of two matrices
print(numpy_arr1 + numpy_arr2)

# Scalar addition to a matrix
print(numpy_arr2 + 7)

# Difference between two matrices
print(numpy_arr1 - numpy_arr2)

#Multiplication of two matrices
print(numpy_arr1*numpy_arr2)

#Division of a matrix by a scalar
print(numpy_arr1 / 2)

#Remainder of a matrix
print(numpy_arr1 % 4)

[[21 23 25 27 29]
 [23 25 27 29 31]
 [25 27 29 31 33]]
[[ 8  9 10 11 12]
 [ 9 10 11 12 13]
 [10 11 12 13 14]]
[[19 19 19 19 19]
 [19 19 19 19 19]
 [19 19 19 19 19]]
[[ 20  42  66  92 120]
 [ 42  66  92 120 150]
 [ 66  92 120 150 182]]
[[10.  10.5 11.  11.5 12. ]
 [10.5 11.  11.5 12.  12.5]
 [11.  11.5 12.  12.5 13. ]]
[[0 1 2 3 0]
 [1 2 3 0 1]
 [2 3 0 1 2]]


**Array Broadcasting**

Two different numpy arrays(2D array) which is a matrix of different dimensions can be added, subtracted and multiplied WHERE the numpy array with small dimension is multiplied to fill the matrix of bigger dimension

In [13]:
arr4 = np.array([[[1,2,3,4],[5,6,7,8]],
                 [[9,10,11,12],[13,14,15,16]]])
arr4.shape

(2, 2, 4)

In [14]:
arr5 = np.array([3,3,3,3])
arr5.shape

(4,)

In [15]:
arr6 = np.array([2,3,4])
arr6.shape

(3,)

In [16]:
arr4 + arr5

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [17]:
arr4 + arr6    #It cannot broadcast since, arr6 is not enough to fill the arr4

ValueError: operands could not be broadcast together with shapes (2,2,4) (3,) 

**ARRAY COMPARISON**

Array comparison returns set of boolean values - True or False

In [ ]:
numPy_arr1 = np.array([[1,3,6],[5,7,9]])
numPy_arr2 = np.array([[2,4,6],[5,7,8]])

print(numPy_arr1 == numPy_arr2)
print(numPy_arr1 != numPy_arr2)
print(numPy_arr1 >= numPy_arr2)
print(numPy_arr1 <= numPy_arr2)

print((numPy_arr1 == numPy_arr2).sum())

**ARRAY INDEXING AND SLICING**

**OTHER WAYS OF CREATING NUMPY ARRAY**

In [ ]:
print(np.ones([2,3])) #Matrix conatining one. Just enter the dimension of the matrix


In [ ]:
print(np.zeros([2,2,3])) #Matrix containing only zeros made by inputing dimension of the matrix

In [ ]:
np.eye(3)    #Identity matrix -> diagonal matrix elements are 1. Input the number of diagnol elements

In [ ]:
# Random vector
print(np.random.rand(3))
print(np.random.rand(2,3))

In [ ]:
#Random matrix
np.random.randn(2,3)

In [ ]:
#Array made up of a fixed value as its elements
np.full([2,3],33)

In [ ]:
#Array made up of a given starting and ending number along with its common difference(increase amount)-> Range specified
np.arange(3,40,2)

In [ ]:
#Equally spaced numbers in a range
np.linspace(3,40,2)

**ARRAY INDEXING AND SPLICING**



In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])
arr3.shape


In [ ]:
#To get a single element from the 3D array
arr3[1,0,2]


In [ ]:
#Subarray using ranges


**Zip function**

Zip function is used to zip an input which is iterable to a tuple

In [ ]:
n_arr1 = np.array([1,2,3])
n_arr2 = np.array([4,5,6])
result = 0
for x,y in zip(n_arr1, n_arr2):
    result += x*y
    
print(result)

**OPERATIONS OF NUMPY** LIKE RESHAPE ETC....